import { Dimensions, StyleSheet} from "react-native";
import { themes } from "../../global/themes";

export const style = StyleSheet.create({

    container:{
    flex: 1,
    backgroundColor:'rgba(0,0,0,0.4)',
    justifyContent:'center',
    alignItems:'center',
  },
  modalContainer:{
    width:'90%',
    backgroundColor:themes.colors.backgroud,
    borderRadius:10,
    paddingBottom:20, 
    maxHeight: '80%', 
  },
  upper:{
    backgroundColor:themes.colors.darkblue,
    paddingVertical:30, 
    borderTopLeftRadius:10,
    borderTopRightRadius:10,
    alignItems:'center',
    justifyContent: 'center', 
  },
  upperText:{
    color:'white',
    fontWeight:'bold',
    fontSize:28, 
    textAlign: 'center',
  },
  itemRow:{
    backgroundColor:'white',
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
    paddingHorizontal:15, 
    paddingVertical:10, 
    marginHorizontal:15, 
    marginVertical:5,
    borderRadius:15,
    shadowColor: "#000", 
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 3,
  },
  itemText:{
    fontSize:22, 
    fontWeight:'500',
    marginLeft:10,
    color: themes.colors.darkblue, 
    flexShrink: 1, 
  },
  icon:{
    color:themes.colors.lightbluu, 
    marginLeft:10,
  },
  user:{
    color:themes.colors.darkblue,
  },
  createButton:{ 
    backgroundColor:themes.colors.ciano,
    marginHorizontal:20,
    paddingVertical:15,
    marginTop:20, 
    borderRadius:15,
    alignItems:'center',
  },
  createButtonText: {
    color:'white',
    fontWeight:'bold',
    fontSize:24, 
  },
  saveButton: { 
    backgroundColor:themes.colors.ciano, 
    marginHorizontal:20,
    paddingVertical:15,
    marginTop:10, 
    borderRadius:15,
    alignItems:'center',
  },
  saveButtonText: {
    color:'white',
    fontWeight:'bold',
    fontSize:24, 
  },
  left:{
    flexDirection:"row",
    alignItems: "center", 
  },
  searchInput: { 
    flex: 1,
    borderWidth: 1,
    borderColor: themes.colors.grayy, 
    backgroundColor: 'white', 
    padding: 12, 
    borderRadius: 8, 
    marginHorizontal: 15,
    marginBottom: 15, 
    fontSize: 18, 
    color: themes.colors.darkblue, 
  },
  searchContainer: { 
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    marginBottom: 10,
    marginTop: 20, 
  },
  listEmptyText: { 
    textAlign: 'center',
    color: themes.colors.dkgrayy,
    fontSize: 16,
    marginTop: 20,
    marginBottom: 20,
  },
});